#!/bin/sh

CHANGES=$(git status -s | grep "zunzuncito/" | wc -l)

if [ $CHANGES -gt 0 ]; then

  COMMITS=$(git rev-list HEAD --count)

  find . -type f -iname "version.py" -print0 | xargs -0 sed -i '' "s/^commits.*/commits = '$((COMMITS + 1))'/g"

  git update-index --again

fi
